import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  zh: {
    // App & Navigation
    app_name: 'AI 智能助手',
    tab_chat: '问答',
    tab_knowledge: '知识库',
    tab_ticket: '工单',
    tab_profile: '我的',

    // Chat Page
    input_placeholder: '描述您遇到的问题...',
    create_ticket: '创建工单',
    history: '历史对话',
    new_chat: '新建对话',
    confirm_new_chat: '创建新对话？',
    confirm_new_chat_desc: '当前对话记录将被保存。您确定要开始新的对话吗？',
    cancel: '取消',
    confirm: '确认',
    no_conversations: '还没有对话记录',
    no_conversations_desc: '试试下面的常见问题，或者直接向我提问',
    loading_conversation: '加载对话记录中...',
    no_history: '暂无历史对话记录',
    loading_history: '加载历史对话...',
    delete_history_confirm_title: '删除历史对话',
    delete_history_confirm_desc: '删除后数据不可恢复，确定要删除该对话吗？',
    dont_show_again: '不再提示',
    confirm_delete_history: '确认删除',
    settings_confirm_before_delete_history: '删除前二次确认',
    settings_confirm_before_delete_history_desc: '删除对话时弹出确认窗口，防止误删',
    continue_asking: '继续问我',
    refresh_questions: '换一换',
    problem_solved: '问题解决了吗？',
    problem_solved_desc: '如果以上方案未能解决您的问题，我可以为您创建工单，由专业工程师为您提供支持。',
    resolved: '已解决',
    switch_human: '如需协助，可转接人工服务',
    ticket_created_success: '工单创建成功！',
    ticket_created_desc: '我们将尽快处理您的问题',
    ai_thinking: '正在识别故障码...',
    ai_thinking_2: '正在查询维修知识库...',
    ai_thinking_3: '正在生成解决方案...',
    problem_resolved_message: '太好了！很高兴能帮到您。如果还有其他问题，随时可以来咨询我。',

    // Ticket Page
    my_tickets: '我的工单',
    search_ticket_placeholder: '搜索工单编号或问题描述...',
    all_tickets: '全部工单',
    processing: '处理中',
    completed: '已完成',
    pending: '待处理',
    all: '全部',
    cancelled: '已取消',
    priority_high: '高',
    priority_medium: '中',
    priority_low: '低',
    ticket_priority_label: '优先级',
    ticket_not_login_hint: '请登录后使用工单功能',
    ticket_no_records: '暂无工单记录',
    ticket_no_match: '未找到匹配的工单',
    ticket_no_records_desc: '遇到问题时，AI助手会为您创建工单',
    ticket_type_report: '故障报修',
    ticket_type_question: '问题咨询',
    ticket_satisfied: '满意',
    ticket_unsatisfied: '不满意',
    ticket_send_message: '发送消息',
    ticket_call_engineer: '致电工程师',
    ticket_create_failed: '创建工单失败',
    ticket_load_failed: '加载工单失败',
    ticket_create_title: '创建工单',
    ticket_consult_ai_first_title: '建议先咨询AI助手',
    ticket_consult_ai_first_desc: '我们的AI助手可以快速帮您解决大部分常见问题。如果AI无法解决，再创建工单也不迟。',
    ticket_go_ai: '去咨询AI助手',
    ticket_continue_create: '继续创建工单',
    ticket_create_default_title: '工单',
    ticket_problem_type_label: '问题类型',
    ticket_device_model_label: '设备型号',
    ticket_device_sn_label: '设备SN',

    // Ticket Form
    ticket_form_title: '创建服务工单',
    ticket_ai_assisting: 'AI 分析中...',
    ticket_ai_assist_fill: 'AI 辅助填写',
    ticket_problem_summary: '问题摘要',
    ticket_problem_summary_placeholder: '简要描述问题...',
    ticket_device_sn_input: '设备 SN 码',
    ticket_additional_notes_optional: '补充说明（选填）',
    ticket_additional_notes_placeholder: '补充其他信息...',
    ticket_submit_includes: '提交后将包含：',
    ticket_submit_item_problem_desc: '问题详细描述',
    ticket_submit_item_device_info: '设备信息和故障时间',
    ticket_creating: '创建中...',
    ticket_confirm_create: '确认创建工单',
    ticket_type_malfunction: '设备故障',
    ticket_type_maintenance: '维护保养',
    ticket_type_consultation: '使用咨询',
    ticket_type_parts: '配件需求',

    // Ticket Detail
    ticket_detail_title: '工单详情',
    ticket_created_prefix: '工单已创建，编号：',
    ticket_engineer_intro_prefix: '您好，我是',
    ticket_engineer_intro_suffix: '，已收到您的工单，正在处理中。',
    ticket_completed_message: '问题已解决，请确认是否满意。如有其他问题，请随时联系。',
    ticket_contains_image: '含图片',
    ticket_created_time: '创建时间',
    ticket_updated_time: '更新时间',
    ticket_assigned_engineer: '负责工程师',
    ticket_estimated_completion: '预计完成时间',
    ticket_problem_description: '问题描述',
    ticket_communication_records: '沟通记录',
    ticket_engineer_fallback: '工程师',
    ticket_service_rating: '服务评价',
    ticket_thanks_feedback: '感谢您的反馈！',
    ticket_input_placeholder: '输入消息与工程师沟通...',
    ticket_engineer_auto_reply: '收到您的消息，我们会尽快为您处理。',

    // Knowledge Page
    knowledge_center_title: '知识库中心',
    knowledge_search_placeholder: '搜索教程、视频、文档...',
    knowledge_category_all: '全部',
    knowledge_category_sales: '销售资料',
    knowledge_category_maintenance: '维护保养',
    knowledge_category_product: '产品资料',
    knowledge_category_company: '公司介绍',
    knowledge_category_training: '培训资料',
    knowledge_load_failed: '加载文件列表失败',
    knowledge_open_failed: '打开文件失败，请稍后重试',
    knowledge_preview_failed: '预览失败，请稍后重试',
    knowledge_download_failed: '下载失败，请稍后重试',
    knowledge_not_found_title: '未找到相关内容',
    knowledge_not_found_desc: '试试其他关键词或浏览不同分类',
    knowledge_file_id: '文件ID',
    knowledge_access_info_unavailable: '无法获取文件访问信息',
    file_type_video: '视频',
    file_type_pdf: 'PDF',
    file_type_image: '图片',
    file_type_excel: 'Excel',
    file_type_ppt: 'PPT',
    file_type_article: '文章',
    file_type_doc: '文档',

    // Profile Page
    settings: '设置',
    settings_general: '通用',
    language: '语言',
    language_setting: '语言设置',
    chinese: '简体中文',
    english: 'English',
    about: '关于',
    version: '版本 1.0.0',
    logout: '退出账号',
    logout_confirm: '确定要退出吗？',
    logout_confirm_desc: '退出后需要重新登录才能使用',
    confirm_logout: '确认退出',
    user_role: '用户身份',
    user_role_desc: '选择您的身份以获得对应服务',
    enduser: '终端用户',
    enduser_desc: '个人/家庭使用',
    dealer: '经销商',
    dealer_desc: '企业/批量使用',
    role_distributor: '经销商',
    role_distributor_desc: '批发/代理商',
    language_select_title: '选择语言',
    profile_info: '个人信息',
    avatar: '头像',
    nickname: '昵称',
    phone_number: '手机号',
    edit_nickname: '修改昵称',
    saving: '保存中...',
    phone_number_cannot_change: '手机号不支持直接修改',
    login_required: '去登录',
    login_desc: '登录后享受完整服务',
    role_current_identity: '当前身份',

    // Login & Register
    login: '登录',
    register: '注册',
    login_phone_label: '请输入手机号',
    login_password_label: '请输入密码',
    login_phone_placeholder: '手机号',
    login_password_placeholder: '密码',
    login_no_account_register: '还没有账号？去注册',
    logging_in: '登录中...',
    register_phone_label: '请输入手机号',
    register_password_label: '请输入密码',
    register_confirm_password_label: '请确认密码',
    register_phone_placeholder: '手机号',
    register_password_placeholder: '密码（至少6位）',
    register_confirm_password_placeholder: '再次输入密码',
    register_has_account_login: '已有账号？去登录',
    registering: '注册中...',
    validation_phone_required: '请输入手机号',
    validation_phone_invalid: '请输入正确的手机号',
    validation_password_required: '请输入密码',
    validation_password_min6: '密码长度不能少于6位',
    validation_confirm_password_required: '请确认密码',
    validation_password_mismatch: '两次输入的密码不一致',
    login_failed_default: '登录失败，请检查手机号和密码',
    register_failed_default: '注册失败，请稍后重试',

    // Profile Info
    profile_nickname_required: '昵称不能为空',
    profile_nickname_too_long: '昵称长度不能超过20个字符',
    profile_update_failed: '更新失败，请稍后重试',
    profile_select_image_file: '请选择图片文件',
    profile_image_size_limit: '图片大小不能超过5MB',
    profile_upload_failed: '上传失败，请稍后重试',
    image_avatar_alt: '头像',
    image_uploaded_alt: '上传的图片',

    // Chat extra
    thinking_active: '思考中…',
    thinking_view_process: '查看思考过程',
    thinking_paused: '思考已暂停',
    citation_source: '来源',
    image_invalid_format: '仅支持 JPG、PNG、WEBP 格式的图片',
    image_too_large_10mb: '图片大小不能超过 10MB',
    send_tip_image_recognizing: '图片正在识别中，请稍候...',
    send_tip_image_failed: '存在识别失败的图片，请重试或删除',
    send_tip_input_or_image: '请输入消息或上传图片',
    ai_no_reply_retry: '抱歉，没有收到回复。请稍后重试。',
    ai_image_process_error: '抱歉，处理图片时出现了错误。请稍后重试。',
    ai_no_reply_simple: '抱歉，我没有收到回复。请重试。',
    knowledge_doc_default: '知识库文档',
    reference_default: '参考资料',
    ai_error_prefix: '抱歉，我遇到了问题：',
    ai_error_network_hint: '请检查网络连接或稍后再试。',
    ai_stop_suffix: '已停止生成',

    // Voice input
    voice_unsupported: '当前浏览器不支持语音输入，请使用 Chrome 或 Edge',
    voice_permission_denied: '麦克风权限被拒绝',
    voice_network_error: '请检查网络连接',
    voice_listening: '正在聆听...',

    // Common
    close: '关闭',
    save: '保存',
    edit: '编辑',
    delete: '删除',
    back: '返回',
    next: '下一步',
    submit: '提交',
    loading: '加载中...',
    retry: '重试',
    view: '预览',
    download: '下载',
    error: '错误',
    success: '成功',
  },
  en: {
    // App & Navigation
    app_name: 'AI Assistant',
    tab_chat: 'Chat',
    tab_knowledge: 'Knowledge',
    tab_ticket: 'Tickets',
    tab_profile: 'Profile',

    // Chat Page
    input_placeholder: 'Describe your issue...',
    create_ticket: 'Create Ticket',
    history: 'History',
    new_chat: 'New Chat',
    confirm_new_chat: 'Create New Chat?',
    confirm_new_chat_desc: 'Current conversation will be saved. Are you sure you want to start a new conversation?',
    cancel: 'Cancel',
    confirm: 'Confirm',
    no_conversations: 'No conversations yet',
    no_conversations_desc: 'Try the common questions below, or ask me directly',
    loading_conversation: 'Loading conversation...',
    no_history: 'No conversation history',
    loading_history: 'Loading history...',
    delete_history_confirm_title: 'Delete conversation',
    delete_history_confirm_desc: 'Data cannot be recovered after deletion. Are you sure?',
    dont_show_again: "Don't show again",
    confirm_delete_history: 'Delete',
    settings_confirm_before_delete_history: 'Confirm before deleting',
    settings_confirm_before_delete_history_desc: 'Show a confirmation dialog when deleting a conversation',
    continue_asking: 'Continue Asking',
    refresh_questions: 'Refresh',
    problem_solved: 'Problem Solved?',
    problem_solved_desc: 'If the above solution did not solve your problem, I can create a ticket for you, and a professional engineer will provide support.',
    resolved: 'Resolved',
    switch_human: 'Need help? Switch to human support',
    ticket_created_success: 'Ticket Created Successfully!',
    ticket_created_desc: 'We will process your issue as soon as possible',
    ai_thinking: 'Identifying error code...',
    ai_thinking_2: 'Querying maintenance knowledge base...',
    ai_thinking_3: 'Generating solution...',
    problem_resolved_message: 'Great! Glad I could help. If you have any other questions, feel free to ask me anytime.',

    // Ticket Page
    my_tickets: 'My Tickets',
    search_ticket_placeholder: 'Search ticket number or description...',
    all_tickets: 'All Tickets',
    processing: 'Processing',
    completed: 'Completed',
    pending: 'Pending',
    all: 'All',
    cancelled: 'Cancelled',
    priority_high: 'High',
    priority_medium: 'Medium',
    priority_low: 'Low',
    ticket_priority_label: 'Priority',
    ticket_not_login_hint: 'Please log in to use ticket features',
    ticket_no_records: 'No ticket records',
    ticket_no_match: 'No matching tickets found',
    ticket_no_records_desc: 'When you encounter an issue, the AI assistant can create a ticket for you',
    ticket_type_report: 'Fault Report',
    ticket_type_question: 'Question',
    ticket_satisfied: 'Satisfied',
    ticket_unsatisfied: 'Unsatisfied',
    ticket_send_message: 'Send Message',
    ticket_call_engineer: 'Call Engineer',
    ticket_create_failed: 'Failed to create ticket',
    ticket_load_failed: 'Failed to load tickets',
    ticket_create_title: 'Create Ticket',
    ticket_consult_ai_first_title: 'Try AI Assistant First',
    ticket_consult_ai_first_desc: 'Our AI assistant can quickly solve most common issues. If AI cannot solve it, you can still create a ticket.',
    ticket_go_ai: 'Ask AI Assistant',
    ticket_continue_create: 'Continue Creating Ticket',
    ticket_create_default_title: 'Ticket',
    ticket_problem_type_label: 'Problem Type',
    ticket_device_model_label: 'Device Model',
    ticket_device_sn_label: 'Device SN',

    // Ticket Form
    ticket_form_title: 'Create Service Ticket',
    ticket_ai_assisting: 'AI analyzing...',
    ticket_ai_assist_fill: 'AI-assisted Fill',
    ticket_problem_summary: 'Problem Summary',
    ticket_problem_summary_placeholder: 'Briefly describe the issue...',
    ticket_device_sn_input: 'Device SN',
    ticket_additional_notes_optional: 'Additional Notes (Optional)',
    ticket_additional_notes_placeholder: 'Add more details...',
    ticket_submit_includes: 'Submission will include:',
    ticket_submit_item_problem_desc: 'Detailed problem description',
    ticket_submit_item_device_info: 'Device information and fault time',
    ticket_creating: 'Creating...',
    ticket_confirm_create: 'Confirm Ticket Creation',
    ticket_type_malfunction: 'Device Malfunction',
    ticket_type_maintenance: 'Maintenance',
    ticket_type_consultation: 'Usage Consultation',
    ticket_type_parts: 'Parts Request',

    // Ticket Detail
    ticket_detail_title: 'Ticket Details',
    ticket_created_prefix: 'Ticket created, ID: ',
    ticket_engineer_intro_prefix: 'Hello, I am ',
    ticket_engineer_intro_suffix: ', and I have received your ticket. It is now being processed.',
    ticket_completed_message: 'The issue has been resolved. Please confirm your satisfaction. If you have other issues, feel free to contact us.',
    ticket_contains_image: 'Includes Image',
    ticket_created_time: 'Created At',
    ticket_updated_time: 'Updated At',
    ticket_assigned_engineer: 'Assigned Engineer',
    ticket_estimated_completion: 'Estimated Completion',
    ticket_problem_description: 'Problem Description',
    ticket_communication_records: 'Communication Records',
    ticket_engineer_fallback: 'Engineer',
    ticket_service_rating: 'Service Rating',
    ticket_thanks_feedback: 'Thanks for your feedback!',
    ticket_input_placeholder: 'Type a message to communicate with the engineer...',
    ticket_engineer_auto_reply: 'We have received your message and will handle it as soon as possible.',

    // Knowledge Page
    knowledge_center_title: 'Knowledge Center',
    knowledge_search_placeholder: 'Search tutorials, videos, and documents...',
    knowledge_category_all: 'All',
    knowledge_category_sales: 'Sales Materials',
    knowledge_category_maintenance: 'Maintenance',
    knowledge_category_product: 'Product Materials',
    knowledge_category_company: 'Company Intro',
    knowledge_category_training: 'Training Materials',
    knowledge_load_failed: 'Failed to load file list',
    knowledge_open_failed: 'Failed to open file. Please try again later',
    knowledge_preview_failed: 'Preview failed. Please try again later',
    knowledge_download_failed: 'Download failed. Please try again later',
    knowledge_not_found_title: 'No matching content found',
    knowledge_not_found_desc: 'Try different keywords or browse another category',
    knowledge_file_id: 'File ID',
    knowledge_access_info_unavailable: 'Unable to get file access info',
    file_type_video: 'Video',
    file_type_pdf: 'PDF',
    file_type_image: 'Image',
    file_type_excel: 'Excel',
    file_type_ppt: 'PPT',
    file_type_article: 'Article',
    file_type_doc: 'Document',

    // Profile Page
    settings: 'Settings',
    settings_general: 'General',
    language: 'Language',
    language_setting: 'Language Settings',
    chinese: '简体中文',
    english: 'English',
    about: 'About',
    version: 'Version 1.0.0',
    logout: 'Logout',
    logout_confirm: 'Are you sure you want to logout?',
    logout_confirm_desc: 'You will need to login again to use the service',
    confirm_logout: 'Confirm Logout',
    user_role: 'User Role',
    user_role_desc: 'Select your role to get corresponding services',
    enduser: 'End User',
    enduser_desc: 'Personal/Home Use',
    dealer: 'Dealer',
    dealer_desc: 'Business/Bulk Use',
    role_distributor: 'Distributor',
    role_distributor_desc: 'Wholesale/Agent',
    language_select_title: 'Select Language',
    profile_info: 'Profile Information',
    avatar: 'Avatar',
    nickname: 'Nickname',
    phone_number: 'Phone Number',
    edit_nickname: 'Edit Nickname',
    saving: 'Saving...',
    phone_number_cannot_change: 'Phone number cannot be changed directly',
    login_required: 'Login',
    login_desc: 'Login to enjoy full service',
    role_current_identity: 'Current Role',

    // Login & Register
    login: 'Login',
    register: 'Register',
    login_phone_label: 'Phone Number',
    login_password_label: 'Password',
    login_phone_placeholder: 'Phone number',
    login_password_placeholder: 'Password',
    login_no_account_register: "No account yet? Register",
    logging_in: 'Logging in...',
    register_phone_label: 'Phone Number',
    register_password_label: 'Password',
    register_confirm_password_label: 'Confirm Password',
    register_phone_placeholder: 'Phone number',
    register_password_placeholder: 'Password (at least 6 characters)',
    register_confirm_password_placeholder: 'Enter password again',
    register_has_account_login: 'Already have an account? Login',
    registering: 'Registering...',
    validation_phone_required: 'Please enter phone number',
    validation_phone_invalid: 'Please enter a valid phone number',
    validation_password_required: 'Please enter password',
    validation_password_min6: 'Password must be at least 6 characters',
    validation_confirm_password_required: 'Please confirm password',
    validation_password_mismatch: 'Passwords do not match',
    login_failed_default: 'Login failed. Please check your phone number and password',
    register_failed_default: 'Registration failed. Please try again later',

    // Profile Info
    profile_nickname_required: 'Nickname cannot be empty',
    profile_nickname_too_long: 'Nickname cannot exceed 20 characters',
    profile_update_failed: 'Update failed. Please try again later',
    profile_select_image_file: 'Please select an image file',
    profile_image_size_limit: 'Image size cannot exceed 5MB',
    profile_upload_failed: 'Upload failed. Please try again later',
    image_avatar_alt: 'Avatar',
    image_uploaded_alt: 'Uploaded image',

    // Chat extra
    thinking_active: 'Thinking...',
    thinking_view_process: 'View reasoning process',
    thinking_paused: 'Thinking paused',
    citation_source: 'Source',
    image_invalid_format: 'Only JPG, PNG, and WEBP images are supported',
    image_too_large_10mb: 'Image size cannot exceed 10MB',
    send_tip_image_recognizing: 'Image is being recognized, please wait...',
    send_tip_image_failed: 'Some images failed to recognize. Please retry or remove them',
    send_tip_input_or_image: 'Please enter a message or upload an image',
    ai_no_reply_retry: 'Sorry, no response was received. Please try again later.',
    ai_image_process_error: 'Sorry, there was an error processing the image. Please try again later.',
    ai_no_reply_simple: 'Sorry, I did not receive a response. Please try again.',
    knowledge_doc_default: 'Knowledge Base Document',
    reference_default: 'Reference',
    ai_error_prefix: 'Sorry, I encountered an issue: ',
    ai_error_network_hint: 'Please check your network connection or try again later.',
    ai_stop_suffix: 'Generation stopped',

    // Voice input
    voice_unsupported: 'Voice input is not supported. Please use Chrome or Edge',
    voice_permission_denied: 'Microphone permission denied',
    voice_network_error: 'Please check your network connection',
    voice_listening: 'Listening...',

    // Common
    close: 'Close',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    back: 'Back',
    next: 'Next',
    submit: 'Submit',
    loading: 'Loading...',
    retry: 'Retry',
    view: 'Preview',
    download: 'Download',
    error: 'Error',
    success: 'Success',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    // Load from localStorage on mount
    const saved = localStorage.getItem('app_language');
    return (saved === 'zh' || saved === 'en') ? saved : 'zh';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.zh] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
